import type { CSSProperties } from 'react';
import { theme } from '../../styles/theme';

export const s: Record<string, CSSProperties> = {
  searchRow: { display: 'flex', gap: '8px' },
  searchInput: { flex: 1, background: theme.bg.tertiary, border: `1px solid ${theme.border.subtle}`, borderRadius: '8px', padding: '10px 14px', fontSize: '14px', fontWeight: 500, color: theme.text.primary, outline: 'none', fontFamily: 'inherit', minWidth: 0 },
  searchBtn: { padding: '10px 20px', background: 'rgba(139,92,246,0.15)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '8px', cursor: 'pointer', fontFamily: 'inherit', fontSize: '14px', fontWeight: 700, color: '#8b5cf6', textTransform: 'uppercase', letterSpacing: '0.5px', flexShrink: 0 },
  tableInfo: { display: 'flex', justifyContent: 'flex-end' },
  tableInfoText: { fontSize: '12px', color: theme.text.muted },
  tableWrap: { overflow: 'auto', background: theme.bg.card, border: `1px solid ${theme.border.subtle}`, borderRadius: theme.radius.md },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '13px' },
  th: { padding: '10px 12px', textAlign: 'left', fontSize: '11px', fontWeight: 700, color: theme.text.muted, textTransform: 'uppercase', letterSpacing: '0.5px', borderBottom: `1px solid ${theme.border.subtle}`, background: theme.bg.tertiary, fontFamily: 'inherit', whiteSpace: 'nowrap' },
  td: { padding: '10px 12px', borderBottom: `1px solid ${theme.border.subtle}`, verticalAlign: 'middle' },
  emptyTd: { padding: '24px 12px', textAlign: 'center', color: theme.text.muted, fontSize: '13px' },
  username: { fontWeight: 700, color: theme.text.primary, fontSize: '13px' },
  email: { color: theme.text.muted, fontSize: '12px' },
  level: { fontWeight: 700, color: '#8b5cf6', fontSize: '13px', fontFamily: '"JetBrains Mono", monospace' },
  vipBadge: { fontSize: '11px', fontWeight: 700, padding: '2px 6px', borderRadius: '4px', border: '1px solid', textTransform: 'uppercase', letterSpacing: '0.5px' },
  statusBadge: { fontSize: '11px', fontWeight: 700, padding: '2px 8px', borderRadius: '4px', textTransform: 'uppercase', letterSpacing: '0.5px' },
  statusActive: { background: 'rgba(52,211,153,0.1)', color: theme.success, border: '1px solid rgba(52,211,153,0.25)' },
  statusSuspended: { background: 'rgba(251,191,36,0.1)', color: theme.warning, border: '1px solid rgba(251,191,36,0.25)' },
  statusBanned: { background: 'rgba(248,113,113,0.1)', color: theme.danger, border: '1px solid rgba(248,113,113,0.25)' },
  role: { fontSize: '12px', fontWeight: 600, color: theme.text.secondary },
  date: { fontSize: '12px', color: theme.text.muted, whiteSpace: 'nowrap' },
  actionBtns: { display: 'flex', gap: '4px', flexWrap: 'wrap' },
  actionBtnGreen: { padding: '3px 8px', background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.25)', borderRadius: '4px', color: theme.success, fontSize: '11px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  actionBtnYellow: { padding: '3px 8px', background: 'rgba(251,191,36,0.1)', border: '1px solid rgba(251,191,36,0.25)', borderRadius: '4px', color: theme.warning, fontSize: '11px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  actionBtnRed: { padding: '3px 8px', background: 'rgba(248,113,113,0.1)', border: '1px solid rgba(248,113,113,0.25)', borderRadius: '4px', color: theme.danger, fontSize: '11px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  actionBtnPurple: { padding: '3px 8px', background: 'rgba(139,92,246,0.1)', border: '1px solid rgba(139,92,246,0.25)', borderRadius: '4px', color: '#8b5cf6', fontSize: '11px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  actionBtnBlue: { padding: '3px 8px', background: 'rgba(56,189,248,0.1)', border: '1px solid rgba(56,189,248,0.25)', borderRadius: '4px', color: '#38bdf8', fontSize: '11px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  filterRow: { display: 'flex', gap: '6px', flexWrap: 'wrap', marginBottom: '12px' },
  filterBtn: { padding: '6px 14px', background: 'transparent', border: `1px solid ${theme.border.subtle}`, borderRadius: theme.radius.md, color: theme.text.muted, fontSize: '12px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  filterBtnActive: { padding: '6px 14px', background: 'rgba(139,92,246,0.12)', border: `1px solid ${theme.accent.purple}`, borderRadius: theme.radius.md, color: theme.accent.purple, fontSize: '12px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', textTransform: 'uppercase', letterSpacing: '0.3px' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(14,10,22,0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalCard: { display: 'flex', flexDirection: 'column', gap: '10px', padding: '24px', background: theme.bg.card, border: `1px solid ${theme.border.medium}`, borderRadius: theme.radius.lg, width: '360px', maxWidth: '90vw' },
  modalTitle: { fontSize: '16px', fontWeight: 800, color: theme.text.primary, fontFamily: 'inherit', letterSpacing: '0.5px', marginBottom: '4px' },
  formInput: { width: '100%', padding: '10px 12px', background: theme.bg.primary, border: `1px solid ${theme.border.medium}`, borderRadius: theme.radius.md, color: theme.text.primary, fontSize: '14px', outline: 'none', fontFamily: 'inherit', boxSizing: 'border-box' },
  createFormCard: { display: 'flex', flexDirection: 'column', gap: '8px', padding: '16px', background: theme.bg.tertiary, border: `1px solid ${theme.border.subtle}`, borderRadius: theme.radius.md, marginBottom: '12px' },
  formLabel: { fontSize: '11px', fontWeight: 600, color: theme.text.muted, textTransform: 'uppercase', letterSpacing: '0.3px', marginBottom: '2px' },
  formRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  target: { fontSize: '12px', color: theme.text.secondary, fontFamily: '"JetBrains Mono", monospace' },
  statsGrid: { display: 'grid', gap: '10px' },
};
